## Random Data Distribution

In [1]:
### Data Distribution:
## is a list of all possible values,
## and how often each value occurs.

### Random Distribution:
## is a set of random numbers that follow a certain
## probability density function.

### Probability Density Function:
## A function that describes a continuous probability.
## i.e. probability of all values in an array.

In [9]:
## Generating a 1-D array containing 100 values,
## where each value has to be 3, 5, 7, or 9.

from numpy import random

## the sum of all probability numbers should be 1
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.4, 0.2], size=(100))

print(x)

[5 3 7 5 5 5 7 3 7 9 9 7 3 9 7 5 5 5 5 5 9 5 5 9 3 7 7 5 7 9 5 9 3 7 7 5 3
 9 5 9 5 5 5 5 7 3 7 5 9 9 9 9 9 9 7 7 3 7 5 7 7 7 5 5 5 5 9 7 7 7 5 7 3 7
 5 9 7 5 5 9 5 5 5 9 5 3 5 7 5 7 7 7 9 9 7 7 3 9 5 9]


In [11]:
## Generating a 2-D array
from numpy import random

x = random.choice([2, 4, 6, 8], p=[0.2, 0.3, 0.4, 0.1], size=(3,5))

print(x)

[[4 4 4 6 2]
 [6 8 6 2 4]
 [4 6 6 4 6]]
