## Random Numbers in NumPy

In [13]:
import numpy as np

### Generate Random Number

In [21]:
from numpy import random

x = random.randint(100)  ## generate random integer
y = random.rand()  ## generate random float

print(x)
print(y)

79
0.817194316129545


### ## Generaet random Array

In [31]:
## Generaet random integer array
from numpy import random

a = random.randint(100, size=(5))
b = random.randint(100, size=(3,5))

print(a)
print(b)

[21 30 68 26 94]
[[73 60 53 70 89]
 [68 38 43 11 60]
 [ 7 25 76 93 17]]


In [38]:
## Generate random float array
from numpy import random

a = random.rand(5)
b = random.rand(3,5)

print(a)
print(b)

[0.45734321 0.84195594 0.16404892 0.6895257  0.08919286]
[[0.69720397 0.64348302 0.46547369 0.53707489 0.75879009]
 [0.6553419  0.88058486 0.99664928 0.43789716 0.31931315]
 [0.26651184 0.24655305 0.82700644 0.28178565 0.55149288]]


### Generate Rabdom Number From Array

In [41]:
from numpy import random
arr = [3, 5, 7, 9]
x = random.choice(arr)

print(x)

7


In [46]:
## Generate a 2-D array
from numpy import random

arr = range(100)
x = random.choice(arr, size=(3,5))

print(x)

[[29 40 59 93 49]
 [87 19 20 56 34]
 [59 60 64 15 38]]
