## Random Permutations

In [1]:
### Random Permutation of Elements:
## A permutation refers to an arrangement of elements.
## e.g. [3,2,1] is a permutation of [1,2,3] and vice-versa.

## The NumPy Random module provides two methods for this:
## shuffel() and permutation()

### Shuffling Arrays:

In [10]:
## Shuffle means changing arrangement of elements in-place.
## i.e. in the array it self.

## randomly shuffle elements of following array:
## The shuffle() method makes changes to the original array.
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[2 1 5 4 3]


### Generating Permutation of Arrays

In [12]:
## Generating Permutation of elements of following array
## The permutation() method returns a re-arranged array
## (and leaves the original array un-changed)

from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

new_arr = random.permutation(arr)

print(new_arr)
print(arr)

[3 1 2 4 5]
[1 2 3 4 5]
