In [15]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [16]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape =(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [18]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.33086628, -0.53750443,  0.646871  , -0.02652018,  0.28655583,
         0.09555268,  0.54813534,  0.02743833,  0.23461762, -0.07311415]],
      dtype=float32)

In [20]:
tf.nn.softmax(predictions).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.06208441, 0.05049412, 0.16504732, 0.08417021, 0.11511332,
        0.09509858, 0.14952993, 0.08883668, 0.10928716, 0.08033834]],
      dtype=float32)>>

In [21]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [22]:
loss_fn(y_train[:1], predictions).numpy()

2.3528414

In [23]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [24]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2974 - accuracy: 0.9113
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1439 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1068 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0877 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0741 - accuracy: 0.9767


In [25]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0744 - accuracy: 0.9771


[0.07436409592628479, 0.9771000146865845]

In [27]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [28]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.24251827e-08, 5.24038191e-09, 4.88393334e-06, 7.24784259e-05,
        4.52036368e-12, 2.19224248e-07, 2.29139326e-13, 9.99908686e-01,
        6.76536089e-08, 1.36064673e-05],
       [1.79885173e-09, 8.52431753e-04, 9.99133170e-01, 1.53959002e-06,
        4.67999283e-13, 4.59195661e-07, 5.73269467e-08, 1.63225231e-14,
        1.24247799e-05, 2.38751011e-12],
       [4.62937322e-07, 9.99780834e-01, 2.59133631e-05, 1.77366599e-06,
        3.07435903e-06, 3.00776196e-06, 4.27717123e-06, 1.25401319e-04,
        5.51987105e-05, 1.13588847e-07],
       [9.99941111e-01, 3.39185124e-09, 3.60701088e-05, 1.06686095e-07,
        1.26220613e-07, 1.03972638e-06, 8.19415618e-06, 1.13732540e-06,
        2.18399151e-07, 1.20429522e-05],
       [1.90434446e-06, 1.43971413e-09, 7.26212602e-05, 1.14076109e-07,
        9.89042342e-01, 3.56818487e-06, 8.51233472e-06, 2.09722173e-04,
        3.95022698e-06, 1.06573626e-02]], dtype=float32)>