## NumPy Sorting Arrays

In [3]:
import numpy as np

In [5]:
## Sorting means putting elements in an ordered sequence
## Sort the array

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [7]:
## Sort the array alphabetically

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [9]:
## Sort a boolean array

arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


### Sorting a 2-D Array

In [10]:
## If we use the sort() method on a 2-D array,
## both arrays will be sorted.

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
