## NumPy Array Iterating

In [28]:
import numpy as np

In [6]:
## Iterating means going through elements one by one
## Iterate on the elements of the following 1-D array

arr  = np.array([1,2,3])

for i in arr:
    print(i)

1
2
3


### Iterating 2-D Arrays 

In [11]:
## In a 2-D array it will go through all the rows.
## Iterate on the elements of the following 2-D array

arr = np.array([[1,2,3,],[4,5,6]])
print(arr)

for i in arr:
    print(i)


[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]


In [13]:
## Iterate on each scalar element of the 2-D array

arr = np.array([[1,2,3], [4,5,6]])

for i in arr:
    for  j in i:
        print(j)

1
2
3
4
5
6


### Iterating 3-D Arrays

In [15]:
## In a 3-D array it will go through all the 2-D array
## Iterate on the elements of the following 3-D array

arr = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]]])

for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [22]:
## Iterate on each scalar element of the 3-D array

arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


### Iterating Arrays Using nditer()

In [24]:
## Iterate through the following 3-D array

arr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8


### Iterating Array With Different Data Types

In [26]:
## Iterate through the array as a string

arr = np.array([1, 2, 3])

for i in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(i)

b'1'
b'2'
b'3'


### Iterating With Difterent Step Size

In [30]:
## We can use filtering and followed by iteration
## Iterate through every scalar element of the
## 2-D array skipping 1 element.

arr = np.array([[1,2,3,4], [5,6,7,8]])

for i in np.nditer(arr[:, ::2]):
    print(i)

1
3
5
7


### Enumerated Iteration Using ndenumerate()

In [37]:
## Enumeration means mentioning sequence number
## of somethings one by one.
## Enumearate on following 1-D arrays elements

arr = np.array([1,2,3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [38]:
## Enumearate on following 2-D array's elements

arr = np.array([[1,2,3,4], [5,6,7,8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
