## NumPy Array Shape 

In [3]:
import numpy as np

In [5]:
## Print the shape of a 2-D array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [7]:
## Create an array with 5 dimensions using ndmin
## using a vector with values 1,2,3,4
## and verify that last dimension has value 4

arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('shape of the array:', arr.shape)

[[[[[1 2 3 4]]]]]
shape of the array: (1, 1, 1, 1, 4)


## NumPy Array Reshaping

In [11]:
## Reshape from 1-D to 2-D array.
## Convert the following 1-D array with 12 elements
## into a 2-D array.
## The outermost dimmension will have 4 arrays,
## each with 3 elements.

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
## Reshape from 1-D to 3-D array.
## Convert the following 1-D array with 12 elements
## into a 3-D array.
## The outermost dimension will have 2 arrays
## that contains 3 arrays, each with 2 elements.

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [18]:
## Try converting 1-D array with 8 elements
## to a 2-D array with 3 elements 
## in each dimension (will raise an error).

arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(3, 3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

### Returns Copy or View

In [21]:
## Check if the returned array is a copy or a view
## As the example will returns the original array,
## so it is a view.

arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


### Unknown Dimension 

In [25]:
## Convert 1-D array with 8 elemensts to 3-D array
## with 2x2 elements.

arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening the Arrays

In [34]:
## Flattening array mreans convrerting 
## a multidimensional array into a 1-D array.
## We can use reshape(-1) to do this
## Convert the array into a 1-D array

arr = np.array([[1,2,3], [4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]
