## NumPy Data Types

In [5]:
## complex number
a = complex(2,5)
print(a)

(2+5j)


In [6]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [10]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [15]:
## creating Arrays with a defined Data Type
## creating an Array with data type string:
arr = np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [18]:
## creating an array with data type 4 bytes integer
arr = np.array([1,2,3,4], dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [20]:
## valueError
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

### Converting Data Types on Existing Arrays

In [24]:
## change data type from float to integer by using
## 'i' as parameter value
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [26]:
## change data type from float to integer by using
## int as parameter value
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [27]:
## change data type from integer to boolean
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
