# Transpose and Flatten

In [1]:
import numpy as np

In [3]:
## uses of transpose() function

my_arr = np.array([[1, 2, 3],
                   [4, 5, 6]])

newarr = np.transpose(my_arr)
print(newarr)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
## uses of flatten() function

my_arr = np.array([[1, 2, 3],
                   [4, 5, 6]])

newarr = my_arr.flatten()
print(newarr)

[1 2 3 4 5 6]


## Zeros and Ones

In [14]:
print(np.zeros((2,3), dtype = int))
print(np.ones((3,2), dtype = int))

[[0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]
 [1 1]]


In [19]:
## for n dimensional array

n = tuple(map(int, input().split()))

z = np.zeros(n, dtype = int)
o = np.ones(n, dtype = int)

print(z)
print(o)

3 2 3
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


## Eye and Identitty

In [33]:
## Eye
print(np.eye(5, 5, k=-1))

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [37]:
## Identity
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [53]:
## problem

n, m = map(int, input().split(' '))
np.set_printoptions(sign=' ')
arr = np.eye(n,m)

print(arr)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [60]:
n = input()
np.set_printoptions(sign=' ')
print(n)

ab
ab


In [64]:
import numpy as np

n, m = map(int, input().split())

a = np.array([input().split() for _ in range(n)], int)
b = np.array([input().split() for _ in range(n)], int)

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b).astype(int))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]


## Floor, Ceil and Rint

In [84]:
## floor
## the tool floor returns the floor of the input element-wise.
import numpy as np

my_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

print(np.floor(my_array))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [80]:
## Ceil
## The tool ceil returns the celing of the input element-wise.

my_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

print(np.ceil(my_array))

[  2.   3.   4.   5.   6.   7.   8.   9.  10.]


In [82]:
## rint
## The rint tool rounds to the nearest integer of inputelement-wise.

my_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

print(np.rint(my_array))

[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [91]:
print (np.array([1.123456789]))
np.set_printoptions(precision = 4)
print (np.array([1.123456789]))

[ 1.1235]
[ 1.1235]
