## NumPy Joining Array

In [2]:
import numpy as np

In [7]:
## Joining means putting contents of two or more arrays
## in a single array.
## Join two arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)


[1 2 3 4 5 6]


In [14]:
## join 2-D arrays along rows (axis=1)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### Joining Arrays Using Stack Functions

In [22]:
## join two array using stack() function

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


### Stacking Along Rows

In [36]:
## NumPy provides a helper function: hstack()
## to stack along rows.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


### Stacking Along Columns

In [34]:
## NumPy provides a helper function: vstack()
## to stack along columns.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


### Stacking Along Height (depth)

In [38]:
## NumPy provides a helper function: dstack()
## to stack along height, which is the same as depth.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
