## NumPy Searching Arrays

In [2]:
import numpy as np

In [4]:
## To search an array, we use the where() method.
## Find the indexes where the value is 4.

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [6]:
## Find the indexes where the values are even.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [8]:
## Find the indexes where the values are odd.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6]),)


### Search Sorted 

In [10]:
## The searchsorted() method is assumed to be
## used on sorted arrays.
## Find the indexes where the value 7 shoiuld be inserted

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)
print(x)

1


### Search From the Right Side

In [4]:
## Find the indexes where the value 7 should be
## inserted, starting from the right.

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


### Multiple Values

In [5]:
## To search for more than one value, use an array
## with the specified values
## Find the indexes where the values 2, 4, and,
## 6 should be inserted.

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]
