## NumPy Array Copy vs View

In [4]:
import numpy as np

In [6]:
## COPY
## make a copy, change the original array, 
## and display both arrays

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [9]:
## VIEW
## make a view, change the original array,
## and display both arrays

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [12]:
## Mke Canges in the VIEW
## Make a view, change the view,
## and display both arrays

arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [13]:
## Check if Arrays Owns it's Data
## Print the value of the base attribute
## to check if an array owns it's data

arr  = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
