# Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

## Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [6]:
import numpy as np

# Create a rank 1 array
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

# Create a rank 2 array
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [17]:
import numpy as np

# Create an array of all zeros
a = np.zeros((2, 2))
print(a)

# Create an array of all ones
b = np.ones((2, 2))
print(b)

# Create a constant array
c = np.full((2, 2), 7)
print(c)

# Create a 2x2 identity matrix
d = np.eye(2)
print(d)

# Create an array filled with random values
e = np.random.random((2, 2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.2173685  0.67612977]
 [0.06214427 0.30284213]]


> **other methods of array creation:**
    <a href="https://numpy.org/doc/stable/user/basics.creation.html#arrays-creation" target="_blank">in the documentation</a>.

## Array indexing
Numpy offers several ways to index into arrays.

### Slicing: 
Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, we must specify a slice for each dimension of the array:

In [31]:
import numpy as np

# Create the following rank 2 array with shape (3,4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77
[[77  3]
 [ 6  7]]


We can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [37]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
# Rank 1 view of the second row of a
row_r1 = a[1, :]
print(row_r1, row_r1.shape)

# Rank 2 view of the second row of a
row_r2 = a[1:2, :]
print(row_r2)

# We can make the same distinction when accessing columns of an array
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]]
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


#### Integer array indexing:
When we index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows us to construct arbitrary arrays using the data from another array. Here is an example:

In [39]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [46]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

print(a)

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


#### Boolean array indexing:
Boolean array indexing lets us pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [50]:
import numpy as np

a = np.array([[1,2], [3,4], [5,6]])

# Find the elements of a that are bigger than 2;
# this returns a numpy array of Booleans of the same
# shape as a, where each slot of bool_idx tells
# whether that element of a is > 2.
bool_idx = (a > 2)

print(bool_idx)


# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


> **to know more:**
    <a href="https://numpy.org/doc/stable/reference/arrays.indexing.html" target="_blank">read the documentation</a>.

## Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that we can use to construct arrays. Numpy tries to guess a datatype when we create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [53]:
import numpy as np

x = np.array([1, 2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

# Force a particular datatype
x = np.array([1,2], dtype=np.int64)
print(x.dtype)

int64
float64
int64


> **all about numpy datatypes:**
    <a href="https://numpy.org/doc/stable/reference/arrays.dtypes.html" target="_blank">read the documentation</a>.

## Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [66]:
import numpy as np

x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print("Addition:")
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
print("\n Subtraction:")
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
print("\n Multiplication:")
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
print("\n Division:")
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
print("\n Square root:")
print(np.sqrt(x))

Addition:
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]

 Subtraction:
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

 Multiplication:
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]

 Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

 Square root:
[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the **`dot`** function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. **`dot`** is available both as a function in the numpy module and as an instance method of array objects:

In [4]:
import numpy as np

x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is **`sum`**:

In [10]:
import numpy as np

x = np.array([[1,2], [3,4]])

# Compute sum of all elements
print('sum of all elements:', np.sum(x))

# Compute sum of each column
print('sum of each column :', np.sum(x, axis=0))

# Compute sum of each row
print('sum of each row    :', np.sum(x, axis=1))

sum of all elements: 10
sum of each column : [4 6]
sum of each row    : [3 7]


> **full list of mathematical functions provided by numpy:**
    <a href="https://numpy.org/doc/stable/reference/routines.math.html" target="_blank">documentation</a>.

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the **`T`** attribute of an array object:

In [16]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)

print('\nTranspose matrix of x:')
print(x.T)

# Note that taking the transpose of a rank 1 array does nothing
v = np.array([1,2,3])
print(v)
print(v.T)

[[1 2]
 [3 4]]

Transpose matrix of x:
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


> **more functions for manipulating arrays:**
    <a href="https://numpy.org/doc/stable/reference/routines.array-manipulation.html" target="_blank">see the full list</a>.

## Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

> **Broadcasting two arrays together follows these 
    <a href="https://cs231n.github.io/python-numpy-tutorial/#numpy" target="_blank">rules</a>.**

In [19]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1, 0, 1])

# Create an empty matrix with the shape as x
y = np.empty_like(x)

# Add the vector v to each row of the nmatrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Here are some applications of broadcasting:

In [26]:
import numpy as np

# Compute outer product of vectors
# v has shape (3,), and w has shape (2,)
v = np.array([1,2,3])
w = np.array([4,5])

# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
print(np.reshape(v, (3,1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])

# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
print(x + v)


# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
print((x.T + w).T)

# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))


# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes our code more concise and faster, so we should strive to use it where possible.