## NumPy Universal Functions

In [1]:
# link: https://www.w3schools.com/python/numpy_ufunc.asp

In [3]:
## Without ufunc, we can use Python's built-in zip() method

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
    z.append(i + j)
print(z)

[5, 7, 9, 11]


In [5]:
## With ufunc, we can use the add() function

import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


## Creating Own ufunc

In [9]:
## create own func for addition

import numpy as np

def myadd(x, y):
    return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


### Check if a Function is a ufunc

In [18]:
## Check if a function is a ufunc
## A ufunc should return <class 'numpy.ufunc'>

import numpy as np

print(type(np.add))

print(type(np.concatenate))


<class 'numpy.ufunc'>
<class 'function'>


In [20]:
## use an if statement to check if the function is a ufunc or not

import numpy as np

if type(np.add) == np.ufunc:
    print('add is ufunc')
else:
    print('add is not ufunc')

add is ufunc


In [23]:
## Add the values in arr1 to the values in arr2

import numpy as np

arr1 = np.array([10,  11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [27]:
##Add, Subtract, Multiply, Divide the values in arr2 from the values in arr1

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

arr_add = np.add(arr1, arr2)
arr_sub = np.subtract(arr1, arr2)
arr_mul = np.multiply(arr1, arr2)
arr_div = np.divide(arr1, arr2)

print(arr_add)
print(arr_sub)
print(arr_mul)
print(arr_div)

[30 41 52 63 74 85]
[-10  -1   8  17  26  35]
[ 200  420  660  920 1200 1500]
[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [29]:
## Raise the valuse in arr1 to the power of values in arr2

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


### Remander

In [33]:
## Both mod() and the remainder() functions return the remainder

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr1 = np.mod(arr1, arr2)
newarr2 = np.remainder(arr1, arr2)

print(newarr1)
print(newarr2)

[ 1  6  3  0  0 27]
[ 1  6  3  0  0 27]


### Quotient and Mod

In [36]:
## Return the quotient and mod

import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


### Absolute Values

In [38]:
## Return the quotient and mod

import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]
