## NumPy Set Operations

In [8]:
## link: https://www.w3schools.com/python/numpy_ufunc_set_operations.asp

import numpy as np

In [4]:
### Create Sets in NumPy:
## We can use NumPy's unique() method to find unique elements from
## any array. E.g. create a set array,
## but the set arrays only be 1-D arrays

## Convert following array with repeated elements to a set.

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)


[1 2 3 4 5 6 7]


### Finding Union

In [6]:
## To find the unique values of two arrays, 
## we use the union1d() method.

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


### Finding Intersection

In [15]:
## To find only the values that arre present in both arrays,
## we use the intersect1d() method.

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

## Note: the intersect1d() method takes an optional argument
## assume_unique, which if set to True can speed up computation.
## It should always be set to True when dealing with sets.

[3 4]


### Finding Difference

In [17]:
## To find only the values in the first set that is NOT
## present in the seconds set, use the setdiff1d() method.

## Find the difference of the set1 from set2

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


### Finding Symmetric Difference

In [18]:
## To find the values that are NOT present in BOTH sets,
## we use the setxor1d() method.

## Find the symmetric difference of the set1 and set2

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
