## NumPy Trigonometric Function

In [1]:
## link: https://www.w3schools.com/python/numpy_ufunc_trigonometric.asp

import numpy as np

In [2]:
## Trigonometric Functions:
## NumPy provides the ufunc sin(), cos(), and tan()
## that take values in radians and produce
## the corresponding sin, cos, and tan values.

In [13]:
## find sin, cos, and tan value of pi/2

x = np.sin(np.pi/2)
y = np.cos(np.pi/2)
z = np.tan(np.pi/2)

print(x)
print(y)
print(z)

1.0
6.123233995736766e-17
1.633123935319537e+16


In [6]:
## Find sine values for all of the values in arr

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


### Convert Degrees Into Radians

In [8]:
## radians values are pi/180 * degree_values.
## Convert all of the values in following array to radians

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


### Radians to Degrees

In [14]:
## Convert all of the values in following array to degree

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


### Finding Angles

In [17]:
## Finding angles from values of sin, cos, tan.
## E.g. sin, cos, and tan inverse (arcsin, arccos, arctan)

## NumPy provides ufuncs arcsin(), arccos(), and arctan() that produce
## radian values for corresponding sin, cos, and tan values given.

## Find the angle of 1.0

x = np.arcsin(1.0)

print(x)

1.5707963267948966


### Angles of Each Value in Arrays

In [19]:
## Find the angle for all of the sine values in athe array

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


### Hypotenues

In [20]:
## Finding hypotenues using pythagoras theorem in NumPy.
## NumPy provides the hypot() function that takes the base
## and perpendicular values and produces hypothenues
## ased on pythagoras theorem.

## Find the hypotenues for 4 base and 3 perpendicular

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0
