## NumPy Summations

In [3]:
## Addition is done between two arguments whereas
## summation happens over n elements.

# add and sum the values in arr1 to the values in arr2

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr1 = np.add(arr1, arr2)
newarr2 = np.sum([arr1, arr2])

print(newarr1)
print(newarr2)

[2 4 6]
12


### Summation Over an Axis

In [2]:
## If you specify axis=1, NumPy will sum the numbers in each arrat.

## Perform summation in the following array over 1st axis

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
arr3 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2, arr3], axis=1)

print(newarr)

[6 6 6]


### Cummulative Sum

In [3]:
## Cummulative sum means partially adding the elements in array.
## E.g. The partial sum of [1, 2, 3, 4] 
## would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].
## Perfom partial sum with the cumsum() function.

import numpy as np

arr = np.array([1 , 2, 3, 4])

newarr = np.cumsum(arr)

print(newarr)

[ 1  3  6 10]
