## NumPy Array

In [3]:
import numpy

In [5]:
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [11]:
print(np.__version__)

1.18.5


In [13]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
### 0-D Array

In [18]:
arr = np.array(42)
print(arr)

42


In [21]:
## 1-D Array
arr  = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [24]:
## 2-D Array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [26]:
## 3-D Array
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [29]:
a = np.array(42)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [34]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('num of dimension: ', arr.ndim)

[[[[[1 2 3 4]]]]]
num of dimension:  5


In [36]:
arr = np.array([1,2,34,5])
print(arr[2])

34


In [38]:
## access 2-D array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st dim: ', arr[0,1])

2nd element on 1st dim:  2


In [43]:
## access 3-D array
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [47]:
## negative indexing
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd dim: ', arr[1, -1])

last element from 2nd dim:  10


### Slicing Arrays 

In [52]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [54]:
## Negative Slicing
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [57]:
## step
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])
print(arr[::2])

[2 4]
[1 3 5 7]


In [58]:
## Slicing 2-D Array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]
